basePath: /
definitions:
  models.Feature:
    properties:
      amount:
        type: string
      icon:
        type: string
      id:
        type: string
      subtitle:
        type: string
      title:
        type: string
    type: object
  models.FeatureResponse:
    properties:
      data:
        $ref: '#/definitions/models.Feature'
    type: object
  models.FeaturesResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/models.Feature'
        type: array
    type: object
  models.Menu:
    properties:
      bgColor:
        type: string
      icon:
        type: string
      iconColor:
        type: string
      id:
        type: string
      route:
        type: string
      title:
        type: string
    type: object
  models.MenuResponse:
    properties:
      data:
        $ref: '#/definitions/models.Menu'
    type: object
  models.MenusResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/models.Menu'
        type: array
    type: object
  models.Product:
    properties:
      ShopID:
        type: integer
      category:
        type: string
      coin:
        type: string
      createdAt:
        type: string
      description:
        type: string
      diskon:
        type: string
      durasi:
        type: string
      id:
        type: string
      image:
        type: string
      isFavorite:
        type: boolean
      isMall:
        type: boolean
      isOri:
        type: boolean
      kota:
        type: string
      price:
        type: string
      promo:
        type: string
      rating:
        type: number
      ratingCount:
        type: integer
      shipping:
        type: string
      shopDetail:
        $ref: '#/definitions/models.Shop'
      sold:
        type: integer
      status:
        type: string
      title:
        type: string
    type: object
  models.ProductResponse:
    properties:
      data:
        $ref: '#/definitions/models.Product'
    type: object
  models.ProductsResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/models.Product'
        type: array
    type: object
  models.Shop:
    properties:
      chatPercentage:
        type: integer
      location:
        type: string
      name:
        type: string
      productCount:
        type: integer
      rating:
        type: number
    type: object
host: golang-shopee-clone-production.up.railway.app
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server for a Shopee-like API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Golang Shopee API
  version: "1.0"
paths:
  /features:
    get:
      consumes:
      - application/json
      description: Get all features
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.FeaturesResponse'
      summary: Show all features
      tags:
      - features
    post:
      consumes:
      - application/json
      description: Create a new feature
      parameters:
      - description: Feature
        in: body
        name: feature
        required: true
        schema:
          $ref: '#/definitions/models.Feature'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.FeatureResponse'
      summary: Create a new feature
      tags:
      - features
  /menus:
    get:
      consumes:
      - application/json
      description: Get all menus
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.MenusResponse'
      summary: Show all menus
      tags:
      - menus
    post:
      consumes:
      - application/json
      description: Create a new menu
      parameters:
      - description: Menu
        in: body
        name: menu
        required: true
        schema:
          $ref: '#/definitions/models.Menu'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.MenuResponse'
      summary: Create a new menu
      tags:
      - menus
  /products:
    get:
      consumes:
      - application/json
      description: Get all products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ProductsResponse'
      summary: Show all products
      tags:
      - products
    post:
      consumes:
      - application/json
      description: Create a new product
      parameters:
      - description: Product JSON
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ProductResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Create a product
      tags:
      - products
  /products/{id}:
    delete:
      consumes:
      - application/json
      description: Delete product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Delete a product
      tags:
      - products
    get:
      consumes:
      - application/json
      description: Get product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ProductResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Show a product
      tags:
      - products
    put:
      consumes:
      - application/json
      description: Update product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      - description: Product JSON
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Update a product
      tags:
      - products
schemes:
- https
swagger: "2.0"
