basePath: /
definitions:
  models.Feature:
    properties:
      amount:
        type: string
      icon:
        type: string
      id:
        type: string
      subtitle:
        type: string
      title:
        type: string
    type: object
  models.Menu:
    properties:
      bgColor:
        type: string
      icon:
        type: string
      iconColor:
        type: string
      id:
        type: string
      route:
        type: string
      title:
        type: string
    type: object
  models.Product:
    properties:
      badge:
        type: string
      coin_reward_text:
        type: string
      estimasi_pengiriman:
        type: integer
      harga_promo:
        type: number
      harga_satuan:
        type: number
      id:
        type: string
      image:
        type: string
      jenis:
        type: string
      jumlah:
        type: integer
      live:
        type: boolean
      shop_name:
        type: string
      status:
        type: string
      title:
        type: string
      total_harga:
        type: number
      total_jumlah:
        type: integer
      variant_label:
        type: string
    type: object
host: golang-shopee-clone-production.up.railway.app
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server for a Shopee-like API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Golang Shopee API
  version: "1.0"
paths:
  /features:
    get:
      consumes:
      - application/json
      description: Get all features
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show all features
      tags:
      - features
    post:
      consumes:
      - application/json
      description: Create a new feature
      parameters:
      - description: Feature
        in: body
        name: feature
        required: true
        schema:
          $ref: '#/definitions/models.Feature'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Feature'
      summary: Create a new feature
      tags:
      - features
  /menus:
    get:
      consumes:
      - application/json
      description: Get all menus
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show all menus
      tags:
      - menus
    post:
      consumes:
      - application/json
      description: Create a new menu
      parameters:
      - description: Menu
        in: body
        name: menu
        required: true
        schema:
          $ref: '#/definitions/models.Menu'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Menu'
      summary: Create a new menu
      tags:
      - menus
  /products:
    get:
      consumes:
      - application/json
      description: Get all products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show all products
      tags:
      - products
    post:
      consumes:
      - application/json
      description: Create a new product
      parameters:
      - description: Product JSON
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Create a product
      tags:
      - products
  /products/{id}:
    delete:
      consumes:
      - application/json
      description: Delete product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Delete a product
      tags:
      - products
    get:
      consumes:
      - application/json
      description: Get product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Show a product
      tags:
      - products
    put:
      consumes:
      - application/json
      description: Update product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      - description: Product JSON
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Update a product
      tags:
      - products
schemes:
- https
swagger: "2.0"
